### ISSUE TITLE
Provide release

### ISSUE THREAD

**Issue by halamix2** [SuiMachine/StuntGP-Widescreen-Fix#3]
Can you provide built .exe release?

**Comment by SuiMachine** [comment]
https://github.com/SuiMachine/StuntGP-Widescreen-Fix/releases/latest

There is some other game exe that apparently has a different pattern, but then I had people complaining that replacing the pattern with the one that works for other exe (and that's shorter) breaks it so idk - https://github.com/SuiMachine/StuntGP-Widescreen-Fix/commit/10e384c1af6843363a4a141216c6847856395c14

**Comment by halamix2** [comment]
Thanks :)
~~IIRC that 4:3 ratio is hardcoded in two or three places, I might check that when I get some time~~ Hardcoded in one place, copied to 4 in mem
